### ISSUE TITLE
프로포즈 이벤트_2조

### ISSUE THREAD

**Issue by nayeon1111** [nayeon1111/2_twomorrow#1]
완벽한 결혼을 위한 로맨틱한 프로포즈 계획하기

**Comment by kim-seong-young** [comment]
그럼 우선 아래와 같이 준비해야 할 것 같습니다.

- [ ] 날짜
- [ ] 장소
- [ ] 선물
- [ ] 노래
- [ ] 음식

**Comment by nnhlvb** [comment]
- [ ] 꽃다발
- [ ] 반지
- [ ] 편지
